export default {
  home: {
    title: 'Welcome to SosoDefi',
    intro:
      'SOSODeFi is a one-stop service platform that provides users with simpler and faster operation of investment and financial search. The platform has functions such as mortgage, lending, casting, oracle options, and search.',
    sections: [
      {
        title: "What's SosoDefi",
        content: [
          {
            title: 'SSDF Bags',
            desc: [
              'SSDF Bags are composed of two parts, one of which is the SSDF Bags formed after the optimal asset ratio combination generated by the matching of the oracle and the SSRoi model, PIPELINE, AMM and other intelligent algorithms.',
              'SosoDefi supports option models, so another type of SSDF Bags is generated by matching the SSDF-OPM model and Chainlink oracles through algorithm matching.',
            ],
          },
          {
            title: 'Auto Rates & Rebalancing',
            desc: [
              'Auto Rates is automatic adjustment, mainly responsible for the realization of automatic adjustment and update of the interest rate optimization of the protocol layer smart contract.',
              'Rebalancing is the last and most important constraint of the stable interest rate model is interest rate rebalancing. This is to solve the problem of changes in market conditions or increased Token costs in the SosoDefi Engine Pool.',
            ],
          },
          {
            title: 'sTokens & sDao',
            desc: [
              'sTokens is that every time you do an LP, a corresponding sTokens will be generated. sTokens can be used for secondary circulation on the platform, such as cross-chain mining, auctions, pledges, flash swaps, options, minting, etc.',
              'sDao is to generate a corresponding sDao every time you do an LP. The main function is to vote (create an independent sDao organization), coinage, update exchange rate model, fee structure, reserve pool amount return change, update penalty premium rate model, update or propose New pledge strategy etc.',
            ],
          },
        ],
      },
      {
        title: 'Introduction on Product Functions',
        content: [
          'Mining using deposit',
          'Lightening debit and credit',
          'Cross-chain flow mining',
          'Oracle option',
        ],
      },
      {
        title: 'Partner',
      },
      {
        title: 'Roadmap',
      },
    ],
  },
  ssdf: {
    title: 'SSDF',
    intro:
      'SSDF is the token of the SOSODEFI platform. The platform uses SSDF to realize the circulation of defi assets and make them economically effective. Users use SSDF to realize functions of defi assets such as mortgage debit & credit and financial management. Meanwhile, SSDF will also bring high benefits as an equity token. ',
    sections: [
      {
        title: 'SosoDefi Coin (SSDF)',
        desc: 'Total supply：10亿',
        content: [
          '10% used for sales',
          '90%used for miner, 72% given to miners',
          '90%used for miner, 17% given to technical communities',
          '90%used for miner, 10% given to sDAO organizations, 1% given to foundation',
        ],
      },
      {
        title: 'Circulation of SSDF',
        desc:
          'Simply speaking, SOSODeFi uses robo-advisory algorithms. When used on other DeFi platforms, it can connect the slot mode of SSDF and directly access robo-advisory algorithms. SOSODeFi can also be used directly, which can save handling fees and VM network consumption.',
        content: [
          'Those who hold SSDF will have sTokens, and they can participate in the auction to obtain coinage rights to deduct Gas consumption.',
          'Violations of smart contract strategies or flash swap attacks on the SSDF platform will all be punished under the governance of sDao, and the penalized CDP account SSDF will be directly destroyed to ensure the SSDF deflation.',
          'After the account is cleared by the smart contract for the reason that the user does not turn on the smart anti-clearance system, 80% of the liquidated assets will be used for destruction, and 20% will be used to reward the CDP account which turns on the smart anti-clearance system, thereby increasing the circulation and utilization rate of SSDF.',
        ],
      },
      {
        title: 'Profit model of SSDF',
        content: [
          'SSDF is the native token of SOSODeFi on VM. SSDF is minted when the mainnet is launched, and it is stored in the contract pool. It is distributed as rewards to the SSDF development team, CDP users, and sDao organization. Simply speaking, liquid mining will award every CDP user participating in the SSDF ecosystem.',
          'Every time when some liquid assets (pledge, option, loan) are added to the SSDF with the generation of corresponding sTokens, some fixed stability fees will be put in the reward pool. Stability fees generated by liquid assets will be returned to the CDP account, the development team, and the sDao organization in proportion to the smart contract.',
          'After the liquidity of the SSDF reaches the lock-up level, the smart contract will automatically trigger the native token bidding system, and any CDP account holding sTokens can participate in the bidding (It can also join the sDao organization independently, and after winning the coinage, native tokens will be allocated by sTokens) to win the final coinage. Users who have coinage can use the minted native tokens as gas fee for transactions, and the stability fee generated by the bidding will be put into the reward pool.',
        ],
      },
      {
        title: 'Merged Mining and sDAO Incentive Mechanism ',
        desc:
          'The SSDF liquidity mining is in a form of "merged mining", and all CDP users who participate in mining can maximize their profits.',
        content: [
          "Another form of merged mining is that users participate in an established sDao organization and jointly participate in the liquidity mining of the platform. Liquidity mining does not generate different weights based on a single CDP position and sToken holdings. It will also consider a series of dimensions such as each user's time participation, credit, loan mortgage, and sDAO model participation in governance, so that sToken ranking will not directly affect everyone's mining rights. SSDF measures a suitable interest rate strategy for everyone. In the model of smart contract, everyone can participate in liquidity mining fairly. The resulting income is distributed to the CDP accounts currently participating in sDao by the above attributes.",
          'Liquidity merged mining uses the PIPELINE model algorithm. Bags are jointly packaged according to the current optimal asset portfolio, and then they will be provided for users to choose. Users who choose different merged mining products will receive different TOKEN rewards. The reward amount will be controlled by the dynamic balance algorithm.',
          'SSDF uses a dynamic interest rate model. Each addition of CDP will increase the reward. The initial contract rewards 20 SSDF per block. With the increase of LP, the SSDF awarded by one block will increase by 20% ~ 80%. Take the current 20 as an example, the futural block rewards can be 24 SSDF ~ 36 SSDF. There is no upper limit for liquidity mining. The stronger the liquidity, the higher the CDP account reward.',
        ],
      },
    ],
  },
};
